### ISSUE TITLE
HTML not being created

### ISSUE THREAD

**Issue by smallboxesmedia** [cbenning/fussel#112]
Hi, I'm using Docker on latest macOS. The docker container runs without error and the **_gallery** images are created but the only HTML file created is **index.html**

This is all that appears in the body tag;
`<div id="app" />`

**Comment by smallboxesmedia** [comment]
Hi, I think my error is something to do with this line
`-v /var/run/docker.sock:/var/run/docker.sock \`

I've copied this from the Readme file and tried adding `fussel` to the end to match my container name but not joy.

Any guidance gratefully received please.

**Comment by smallboxesmedia** [comment]
I've discovered my error - `localhost:8888/fussel` and `fussel:8888` are quite different #faceslap

**Comment by cbenning** [comment]
Was there anything @smallboxesmedia  in the documentation that should be updated? Or was it simply a misunderstanding?

**Comment by smallboxesmedia** [comment]
My misunderstanding. I opened the generated HTML and expected to see more code, then when I made a mistake running  my local server and it didn't work I wrongly assumed there was a problem. The advantage of Docker is it lowers the bar of complexity but assumes you know what you're doing :) Welcome to AI :)
