### ISSUE TITLE
Updating site with new photos

### ISSUE THREAD

**Issue by miek770** [cbenning/fussel#18]
When `./generate_site.sh` is called again after photos/albums are added to the INPUT_PATH, is the whole library reconverted or only stuff that has changed?

**Comment by cbenning** [comment]
As of this time, it's just re-building everything (in fact it will delete the previously generated folder when it starts again so be aware of that). However I had thought about skipping files which had already been processed, and allow an optional 'force' to do the current behaviour.  Another good suggestion.

**Comment by miek770** [comment]
Unfortunately it failed before the end for an encoding error. I'll look into it and report back.

**Comment by cbenning** [comment]
Handling encodings is also something I think would be worth spending time on. If you have char samples or anything you are seeing causing problems, please don’t hesitate to send them. I can make another ticket to try and deal with those. As an English speaker it’s way too easy for me to forget about those things, but I want anybody to be able to use this tool. Thanks for digging!

**Comment by miek770** [comment]
Ok I'll be more careful if I encounter others, I renamed those files because even my OS couldn't show them properly (en_CA.utf-8). They must've been copied from iOS with an encoding I'm not familiar with. There should be others in this situation.
