### ISSUE TITLE
Further nested folder causes crash (instead of being ignored)

### ISSUE THREAD

**Issue by miek770** [cbenning/fussel#19]
Hi,

I have a folder achitecture that mostly match what `fussel` expects, but there are a few exceptions (subfolder within some albums). I thought they would be ignored as mentioned in the README but they appear to have caused the app to crash instead:

```
 > Importing album /mnt/Photos/160617 - Photos bedaine Cap-Rouge as '160617 - Photos bedaine Cap-Rouge'
 --> Processing /mnt/Photos/160617 - Photos bedaine Cap-Rouge/JosianneLapierrePhotographie-78.jpg...
 ----> Copying to '/home/fussel/app/fussel/web/public/static/_gallery/albums/160617 - Photos bedaine Cap-Rouge/original_JosianneLapierrePhotographie-78.jpg'
Traceback (most recent call last):
  File "./fussel.py", line 57, in <module>
    generator.generate_site(output_photos_path, output_data_path, http_root)
  File "/home/fussel/app/fussel/generator/generate.py", line 288, in generate_site
    faces, photo_data = self.process_photo(external_path, photo_file, album_folder)
  File "/home/fussel/app/fussel/generator/generate.py", line 28, in process_photo
    shutil.copyfile(photo, new_original_photo)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/Photos/160617 - Photos bedaine Cap-Rouge/JosianneLapierrePhotographie-78.jpg'
```

The picture above is in fact located under: `/mnt/Photos/160617 - Photos bedaine Cap-Rouge/Chambre - s_lection`

...but then I realized I had not set my locale correctly, and there are french accents in there. So I fixed my locale and will retry. The error might go away.

**Comment by miek770** [comment]
Unfortunately it still fails:

```
 > Importing album /mnt/Photos/160617 - Photos bedaine Cap-Rouge as '160617 - Photos bedaine Cap-Rouge'
 --> Processing /mnt/Photos/160617 - Photos bedaine Cap-Rouge/JosianneLapierrePhotographie-78.jpg...
 ----> Copying to '/home/fussel/app/fussel/web/public/static/_gallery/albums/160617 - Photos bedaine Cap-Rouge/original_JosianneLapierrePhotographie-78.jpg'
Traceback (most recent call last):
  File "./fussel.py", line 57, in <module>
    generator.generate_site(output_photos_path, output_data_path, http_root)
  File "/home/fussel/app/fussel/generator/generate.py", line 288, in generate_site
    faces, photo_data = self.process_photo(external_path, photo_file, album_folder)
  File "/home/fussel/app/fussel/generator/generate.py", line 28, in process_photo
    shutil.copyfile(photo, new_original_photo)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/Photos/160617 - Photos bedaine Cap-Rouge/JosianneLapierrePhotographie-78.jpg'
```

From the start it seems to think that the picture is in `/mnt/Photos/160617 - Photos bedaine Cap-Rouge/`, but it isn't. Since this isn't meant to be supported (sub-albums), a simple `try` & `except FileNotFoundError` would be a simple fix (band-aid style). A better fix would be to completely ignore images in subfolders. A suggested future feature (not critical) would be to support subalbums (subfolders).

**Comment by cbenning** [comment]
Thanks for the report. I will fix the bug and also I think a message "skipping" is appropriate. 

WRT the nested albums, definitely it is a possibiltiy, however it is a non-starter to show folders/albums + photos in the same space, because the album view doesn't work that way.

However, a setting perhaps that tells the generator to make all folders it finds into albums and just places them alongside all the other albums is definitely do-able.

**Comment by miek770** [comment]
> WRT the nested albums, definitely it is a possibiltiy, however it is a non-starter to show folders/albums + photos in the same space, because the album view doesn't work that way.
> 
> A setting perhaps that tells the generator to make all folders it finds into albums and just places them alongside all the other albums is definitely do-able. (as opposed to supporting a hierarchichal album system in the app itself)

That would work, perhaps also using the root album title as the flattened album title's prefix? For ex.:

```
.../House
.../House/Garden
.../House/Stairs
````

...could be shown as:

```
House - Garden
House - Stairs
```

I expect users would at least want these subfolders grouped together in the album view.

P.S.: Thanks for your responsiveness!

**Comment by cbenning** [comment]
The tricky part with grouping things together is how do you display a folder that has both photos and folders/albums directly inside it?  

The component that shows the photos cannot show folders, and vice versa.

**Comment by miek770** [comment]
I see, but in my example, if `.../House` included photos as well as its subfolders, you could generate 3 albums:

```
House
House - Garden
House - Stairs
```

Sorry it was ambiguous, but by "grouped together in the album view" I only meant that I'd like them to be adjacent when albums are sorted alphabetically. Using the root album as a prefix for the "subalbum" would accomplish that automatically. They don't actually need to be nested; a flattened album structure is absolutely fine IMO.

A potential error would be if there's already a "root" album with the same name, i.e.:

```
.../House
.../House/Garden
.../House/Stairs
.../House - Garden
```

But then I'd simply fuse `.../House/Garden` and `.../House - Garden` under the same album in the generated site. That'd be the expected behavior IMHO.

**Comment by cbenning** [comment]
That makes sense, and I'm open to that for sure.

**Comment by cbenning** [comment]
@miek770 I'm implemented new logic for directory scanning.

You will find two new configuration options in the env file.

```
# Recursively process sub-folders as albums
RECURSIVE_ALBUMS="true"

# Pattern for album name creation of sub albums
# Following substitutions are available:
# - {parent_album} will be replaced with the parent album
# - {album} will be replaced with the album name
RECURSIVE_ALBUMS_NAME_PATTERN="{parent_album} > {album}"
```

Sub folders will now be scanned and albums created for them based on the pattern you specify. The above pattern will create child albums with the names:

- top
- top > middle
- top > middle > bottom
...and so on

Code is on master branch.

**Comment by cbenning** [comment]
As a followup there is now also the following settting:

```
# Setting to true will force a full rebuild of the gallery photos.
# Setting to false will only generate files which are missing or added
OVERWRITE="false"
```

Album generator will now ignore copying and generating thumbnails for those that already exist. Caveat: face detection still needs to happen as the data maps still need to be rebuilt. Generation is  significantly faster now though. 

For my sample album:
```
OVERWRITE="true"    - Took 1m30.625s
OVERWRITE="false"   - Took 11.523s
```

**Comment by miek770** [comment]
Sorry I missed your responses, I'll try that ASAP and report back. Thanks.

**Comment by miek770** [comment]
> As a followup there is now also the following settting:
> 
> ```
> # Setting to true will force a full rebuild of the gallery photos.
> # Setting to false will only generate files which are missing or added
> OVERWRITE="false"
> ```
> 
> Album generator will now ignore copying and generating thumbnails for those that already exist. Caveat: face detection still needs to happen as the data maps still need to be rebuilt. Generation is significantly faster now though.
> 
> For my sample album:
> 
> ```
> OVERWRITE="true"    - Took 1m30.625s
> OVERWRITE="false"   - Took 11.523s
> ```

That's awesome, and also seems to be working on my end. Will close #18 once the scan completes and I get to test a rescan with no new photo.

**Comment by cbenning** [comment]
@miek770 I think this ticket is done? I've created another ticket to handle the locale issues.

**Comment by miek770** [comment]
Yeah I'm pretty sure it is, I'll close it and reopen it if not. Sorry, got another error and lacked time to pursue further, got a few minutes now.

**Comment by cbenning** [comment]
No worries. I only have bursts of time too. I usually have a couple quiet hours Sunday morning so you get a flurry from me haha.
