### ISSUE TITLE
Ignore files and folders with a name starting with a dot

### ISSUE THREAD

**Issue by miek770** [cbenning/fussel#20]
If it doesn't already, `generate_site.sh` should ignore dotfiles and folders. They are either generated by the system (not the user) and not really photos, or generated by the user and meant to be hidden.

For some reasons, one of my albums had a few dotfiles otherwise named like a photo (with a JPG extension), but they were 4096B big and weren't really pictures. They caused PIL to fail with an `PIL.UnidentifiedImageError`. I removed then and moved on.

**Comment by cbenning** [comment]
Interesting. It should already be ignoring anything starting with a dot. Perhaps a regression though, as I refactored a lot of the directory stuff.

**Comment by cbenning** [comment]
Ok dotfiles should not be skipped all through the tree, not just at the top.
