### ISSUE TITLE
missing previous/next buttons in carousel view

### ISSUE THREAD

**Issue by h4de5** [cbenning/fussel#39]
in the latest version it seems the next and previous buttons are gone: 

it's still possible to navigate using arrow keys - but when you click outside the actual image, the modal closes.

![image](https://user-images.githubusercontent.com/6115324/105819937-2ccaaa80-5fb9-11eb-8e05-beb794b8a03b.png)

**Comment by cbenning** [comment]
Hmm. I upgraded the dependency and didn't notice this. But the package appears to be abandonware. I will test this and see if I can reproduce ite.

**Comment by despair86** [comment]
the carousel no longer works correctly outside of mobile browsers - on a desktop browser the carousel appears _below_ the modal dialogue out of sight
the image will even flash for a split second before the dialogue covers it!

**Comment by cbenning** [comment]
@despair86 the UI tool was abandoned. I've re-written the entire frontend using new components and can be tested out on the v2 branch before it is released if interested

**Comment by h4de5** [comment]
any chance for an updated docker image? or a beta docker release?

**Comment by cbenning** [comment]
@h4de5 I'll make a task and try to get to it in the next day or two if I can find time. Good suggestion.

**Comment by cbenning** [comment]
@h4de5 give this a try:

`
docker run \
      -e PGID=$(id -g) \
      -e PUID=$(id -u) \
      -v <input_dir>:/input:ro \
      -v <output_dir>:/output \
      --label gallery.input_path="/input" \
      --label gallery.output_path="/output" \
      --label gallery.overwrite=False \
      --label albums.recursive=True \
      --label albums.recursive_name_pattern="{parent_album} > {album}" \
      --label people.enable=True \
      --label watermark.enable=True \
      --label watermark.path="web/src/images/fussel-watermark.png" \
      --label watermark.size_ratio=0.3 \
      --label site.http_root="/" \
      --label site.title="Fussel Gallery" \
     -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/cbenning/fussel:2.0.0-rc4
`

**Comment by h4de5** [comment]
is it possible that this image is set to private?

**Comment by cbenning** [comment]
@h4de5 yup sorry. Still getting the hang of using ghcr.io. Should be fixed now, give it a try.

**Comment by h4de5** [comment]
image is now download able, but running failed. just gave it a brief test run, will have a look at my config later on, to check if it is on my side.

![Screenshot_20230216-005854](https://user-images.githubusercontent.com/6115324/219222613-83f4bf09-3daa-4a75-9157-a3ca24546922.png)

**Comment by cbenning** [comment]
It kinda looks like its failing to generate the config. Looks lke you're using docker-compose? Mind sharing your config?
