### ISSUE TITLE
auto rotate images by EXIF

### ISSUE THREAD

**Issue by mavack** [cbenning/fussel#54]
Do you want to add a true/false for auto rotating the images to the correct orientation, your current resizes don't maintain EXIF so the output thumbs are sometimes orientated incorrect. 

There are always ways to retain EXIF which might also allow the devices to draw correct orientation  

Lots of ways to skin this cat, i just did the following which worked for me, but not sure what it would break on. 

```
#            shutil.copyfile(photo, new_original_photo)
            im = Image.open(photo)
            im = ImageOps.exif_transpose(im)
            im.save(new_original_photo)

```

**Comment by cbenning** [comment]
I've implemented your suggestion in the `v2` branch. Please let me know if it works for you?

**Comment by tshrinivasan** [comment]
```
for i  in *.jpg; do exiftran -ia $i; done
```

The above bash command can rotate the images.
I am using this to rotate and verify before publishing.

**Comment by cbenning** [comment]
Should be working in V2
