### ISSUE TITLE
Prefix recursive folder names by parents

### ISSUE THREAD

**Issue by darkdragon-001** [cbenning/fussel#58]
Assume I have the following folder structure
- a
  - foo
- b
  - foo

When generating with recursive enabled, it outputs _all_ images in a folder called `foo`. Maybe it would be better to prefix it (e.g. `a_foo` and `b_foo`).

**Comment by cbenning** [comment]
This seems reasonable.

**Comment by cbenning** [comment]
@darkdragon-001 I can't reproduce the problem you mentioned. Have you perhaps set the `RECURSIVE_ALBUMS_NAME_PATTERN` variable to something else?

Setting to something like:
`RECURSIVE_ALBUMS_NAME_PATTERN="{parent_album}_{album}"`
Should achieve what you're asking?
