### ISSUE TITLE
Lazy load for large galleries

### ISSUE THREAD

**Issue by KillerTic** [cbenning/fussel#68]
I have a gallery with over 300 pictures and that doesn't work.
Something like lazy load to not load all pictures straight away would be good.

**Comment by cbenning** [comment]
Interesting. What browser? My gallery does lazy-load actually. Lazy load is just usually a tag in the HTML to tell the browser what to do I believe.

**Comment by KillerTic** [comment]
Hmm that is odd... I have the current Chrome version installed.

**Comment by cbenning** [comment]
@KillerTic It's been a long time since this was posted. If you're still using the tool, would you be able to check if you can reproduce the issue with the v2-branch?
