### ISSUE TITLE
Photo name? shows as undefined

### ISSUE THREAD

**Issue by rda0** [cbenning/fussel#81]
When opening a photo, the text `undefined` is shown in the lower-left corner. Which should probably show the filename?

![2022-07-05 12_30_34-Window](https://user-images.githubusercontent.com/6731714/177308911-477ce8bd-b356-42c0-b3b8-81352c8029eb.png)

Firefox: 102.0
Chrome: 103.0.5060.66
OS: Debian 11 Bullseye
Python: 3.9.2
Node: v16.15.1
Fussel: 9545f5b

**Comment by Bart1909** [comment]
Same issue here. Did you find a solution?

**Comment by rda0** [comment]
> Same issue here. Did you find a solution?

No, but I also did not look. ;)

**Comment by ElFishi** [comment]
+1

**Comment by swoertz** [comment]
A fix for this issue has been merged into the master branch. Do you have the possibility to confirm if it solves the issue that you've reported @rda0 so that it can be closed?

**Comment by rda0** [comment]
@swoertz I can confirm it is fixed. Thank you 👍
